# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "848be31aea287fd3b09d52647da03aa6"
name = "advanced-shipping-discount"
handle = "advanced-shipping-discount"
application_url = "https://clusters-grave-management-rotation.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "entry-try-shop.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_shipping,write_discounts,write_discounts_allocator_functions,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://clusters-grave-management-rotation.trycloudflare.com/auth/callback",
  "https://clusters-grave-management-rotation.trycloudflare.com/auth/shopify/callback",
  "https://clusters-grave-management-rotation.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
