# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "848be31aea287fd3b09d52647da03aa6"
name = "advanced-shipping-discount"
handle = "advanced-shipping-discount"
application_url = "https://specifics-termination-degrees-regulated.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "entry-try-shop.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_delivery_customizations,read_locations,read_orders,read_products,read_shipping,write_locations,write_orders,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://specifics-termination-degrees-regulated.trycloudflare.com/auth/callback",
  "https://specifics-termination-degrees-regulated.trycloudflare.com/auth/shopify/callback",
  "https://specifics-termination-degrees-regulated.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
